<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>DynamoDB</title>
</head>
<body>
<h1>Thread <?= h($title); ?></h1>

<h3>Thread Body:</h3>
<p style="border: 1px solid gray;"><?= nl2br(h($body)); ?></p>


<h3>Posts:</h3>
<table border="1">
    <thead>
    <tr>
        <th>Time</th>
        <th>User</th>
        <th>Message</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($posts as $post): ?>
        <tr>
            <td><?= $post['PrettyPostedTime']; ?></td>
            <td><a href="mailto:<?= h($post['PostedBy']); ?>"><?= h($post['PostedBy']); ?></a></td>
            <td><?= nl2br(h($post['Body'])); ?></td>
        </tr>
    <?php endforeach; ?>
    <?php if (empty($posts)): ?>
        <tr>
            <td colspan="3" style="text-align: center"> --[ no messages found ... ]--</td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>
<p>(consumed capacity: <?= $consumedCapacity ?>)</p>

<p><a href="/dynamodb/threads">Back to thread list</a></p>

<hr>
<h2>Post your message..</h2>
<form method="POST">
    <textarea name="body" id="" cols="30" rows="10" placeholder="Body" required></textarea>
    <div>
        <label>Email<input type="email" name="email" placeholder="your email" required></label>
    </div>
    <div>
        <button>Submit</button>
    </div>
</form>
</body>
</html>
